apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: web
  remoteWrite: "http://demo-influxdb.monitoring:8086/api/v1/prom/write?u=admin&p=admin&db=prometheus"
  remoteRead: "http://demo-influxdb.monitoring:8086/api/v1/prom/read?u=admin&p=admin&db=prometheus"
  resources:
    requests:
      memory: 400Mi
